name: Docker Build and deploy to K8S

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v2

      - name: ğŸ” Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.rccn.pro
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: ğŸ—ï¸ Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.rccn.pro/alinastore-frontend:latest
          build-args: |
            VITE_API_BASE_URL=https://store.krasapro.pl

      - name: âš™ï¸ Kubernetes context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          namespace: krasa

      - name: ğŸš€ Deploy
        run: kubectl -n krasa rollout restart deployment/alinastore-frontend
